apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: caredevecr.azurecr.io/cassandra:dev
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 9042
