apiVersion: v1
kind: Secret
metadata:
  name: ingress-secret-tls
  namespace: default
data:
  tls.crt: https://raw.githubusercontent.com/shony1989/my-k8s-files/master/ingress-cert.cer
  tls.key: https://raw.githubusercontent.com/shony1989/my-k8s-files/master/ingress-key.key
