apiVersion: v1
kind: Service
metadata:
  name: internal-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks01-subnet"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.232.111.100
  ports:
  - port: 443
  selector:
    app: internal-app
