apiVersion: v1
kind: Service
metadata:
  name: care-event-in-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 9095
  selector:
    app: care-event-in-service
